# automatic dependencies updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" #directory containing package.json
    schedule: 
      interval: "weekly"
    commit-message:
      prefix: "update" #prefix for commit message for automatic updates
