name: Lint and Audit

on: 
  push:
    branches:
      - master # Pipeline executing on master branch when commited


jobs:
  build:
    runs-on: ubuntu-latest # GitHub Actions environment

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 # step to get source code

      - name: Set up Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: '18'

      - name: Install dependencies
        run: npm install 

      - name: Run lint
        run: npm run lint #check code quality

      - name: Run npm audit
        run: npm audit --audit-level=high #checking vulnerabilities